spring:
  application:
    name: oidc

oauth2:
  client:
    google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      discovery_document_uri: https://accounts.google.com/.well-known/openid-configuration
      redirect_uri: http://localhost:8080/login/oauth2/code/google