spring:
  application:
    name: oidc
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        security: DEBUG
